"""add etl job tables

Revision ID: e60f35d796c3
Revises: e15efcff26bf
Create Date: 2026-04-25 15:29:36.696837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e60f35d796c3'
down_revision: Union[str, Sequence[str], None] = 'e15efcff26bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.drop_index(op.f('edge_status_events_recorded_at_idx'), table_name='edge_status_events')
    op.drop_index(op.f('idx_edge_status_events_edge_effective'), table_name='edge_status_events')
    op.drop_index(op.f('idx_edge_status_events_edge_time'), table_name='edge_status_events')
    op.drop_index(op.f('idx_edges_from_station'), table_name='edges')
    op.drop_index(op.f('idx_edges_line'), table_name='edges')
    op.drop_index(op.f('idx_edges_line_from_order'), table_name='edges')
    op.drop_index(op.f('idx_edges_line_to_order'), table_name='edges')
    op.drop_index(op.f('idx_edges_to_station'), table_name='edges')
    op.alter_column('etl_job_runs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('running', 'success', 'failed', name='etl_job_status'),
               existing_nullable=False)
    op.alter_column('etl_job_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_etl_job_runs_started_at'), table_name='etl_job_runs')
    op.create_index('idx_etl_job_runs_started_at', 'etl_job_runs', ['started_at'], unique=False)
    op.alter_column('etl_job_steps', 'status',
               existing_type=sa.TEXT(),
               type_=sa.Enum('running', 'success', 'failed', name='etl_job_status'),
               existing_nullable=False)
    op.alter_column('etl_job_steps', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_holiday_dates_date'), table_name='holiday_dates')
    op.drop_index(op.f('idx_line_status_current_status'), table_name='line_status_current')
    op.drop_index(op.f('idx_line_status_events_category_time'), table_name='line_status_events')
    op.drop_index(op.f('idx_line_status_events_line_effective'), table_name='line_status_events')
    op.drop_index(op.f('idx_line_status_events_line_time'), table_name='line_status_events')
    op.drop_index(op.f('line_status_events_recorded_at_idx'), table_name='line_status_events')
    op.drop_index(op.f('idx_next_departures_departure_at'), table_name='next_departures')
    op.drop_index(op.f('idx_next_departures_service_date_station'), table_name='next_departures')
    op.drop_index(op.f('idx_next_departures_station_line_time'), table_name='next_departures')
    op.drop_index(op.f('next_departures_updated_at_idx'), table_name='next_departures')
    op.create_foreign_key(None, 'next_departures', 'lines', ['line_id'], ['line_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'next_departures', 'stations', ['station_id'], ['station_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('idx_predicted_stop_times_service_date_station'), table_name='predicted_stop_times')
    op.drop_index(op.f('idx_predicted_stop_times_trip_station_time'), table_name='predicted_stop_times')
    op.drop_index(op.f('predicted_stop_times_updated_at_idx'), table_name='predicted_stop_times')
    op.create_foreign_key(None, 'predicted_stop_times', 'stations', ['station_id'], ['station_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('idx_route_request_logs_created_at'), table_name='route_request_logs')
    op.drop_index(op.f('idx_routing_edges_current_base_edge'), table_name='routing_edges_current')
    op.drop_index(op.f('idx_routing_edges_current_base_edge_null_scenario_unique'), table_name='routing_edges_current', postgresql_where='(scenario_id IS NULL)')
    op.drop_index(op.f('idx_routing_edges_current_base_edge_scenario_unique'), table_name='routing_edges_current', postgresql_where='(scenario_id IS NOT NULL)')
    op.drop_index(op.f('idx_routing_edges_current_from_to'), table_name='routing_edges_current')
    op.drop_index(op.f('idx_service_calendar_date_range'), table_name='service_calendar')
    op.drop_index(op.f('idx_service_exceptions_date'), table_name='service_exceptions')
    op.drop_index(op.f('idx_service_exceptions_date_category'), table_name='service_exceptions')
    op.drop_index(op.f('idx_service_exceptions_service_date'), table_name='service_exceptions')
    op.drop_index(op.f('idx_station_lines_line_order'), table_name='station_lines')
    op.drop_index(op.f('idx_station_lines_station_line'), table_name='station_lines')
    op.drop_index(op.f('idx_station_status_current_status'), table_name='station_status_current')
    op.drop_index(op.f('idx_station_status_events_station_effective'), table_name='station_status_events')
    op.drop_index(op.f('idx_station_status_events_station_time'), table_name='station_status_events')
    op.drop_index(op.f('station_status_events_recorded_at_idx'), table_name='station_status_events')
    op.drop_index(op.f('idx_timetable_line_station'), table_name='timetable')
    op.drop_index(op.f('idx_timetable_station'), table_name='timetable')
    op.drop_index(op.f('idx_timetable_trip_sequence'), table_name='timetable')
    op.drop_index(op.f('idx_transfers_from_station'), table_name='transfers')
    op.drop_index(op.f('idx_transfers_to_station'), table_name='transfers')
    op.drop_index(op.f('idx_trip_status_events_trip_effective'), table_name='trip_status_events')
    op.drop_index(op.f('idx_trip_status_events_trip_time'), table_name='trip_status_events')
    op.drop_index(op.f('trip_status_events_recorded_at_idx'), table_name='trip_status_events')
    op.drop_index(op.f('idx_trips_destination_station'), table_name='trips')
    op.drop_index(op.f('idx_trips_line_service_direction'), table_name='trips')
    op.drop_index(op.f('idx_trips_origin_station'), table_name='trips')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_trips_origin_station'), 'trips', ['origin_station_id'], unique=False)
    op.create_index(op.f('idx_trips_line_service_direction'), 'trips', ['line_id', 'service_id', 'direction_id'], unique=False)
    op.create_index(op.f('idx_trips_destination_station'), 'trips', ['destination_station_id'], unique=False)
    op.create_index(op.f('trip_status_events_recorded_at_idx'), 'trip_status_events', [sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_trip_status_events_trip_time'), 'trip_status_events', ['trip_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_trip_status_events_trip_effective'), 'trip_status_events', ['trip_id', sa.literal_column('effective_from DESC')], unique=False)
    op.create_index(op.f('idx_transfers_to_station'), 'transfers', ['to_station_id'], unique=False)
    op.create_index(op.f('idx_transfers_from_station'), 'transfers', ['from_station_id'], unique=False)
    op.create_index(op.f('idx_timetable_trip_sequence'), 'timetable', ['trip_id', 'stop_sequence'], unique=False)
    op.create_index(op.f('idx_timetable_station'), 'timetable', ['station_id'], unique=False)
    op.create_index(op.f('idx_timetable_line_station'), 'timetable', ['line_id', 'station_id'], unique=False)
    op.create_index(op.f('station_status_events_recorded_at_idx'), 'station_status_events', [sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_station_status_events_station_time'), 'station_status_events', ['station_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_station_status_events_station_effective'), 'station_status_events', ['station_id', sa.literal_column('effective_from DESC')], unique=False)
    op.create_index(op.f('idx_station_status_current_status'), 'station_status_current', ['status'], unique=False)
    op.create_index(op.f('idx_station_lines_station_line'), 'station_lines', ['station_id', 'line_id'], unique=False)
    op.create_index(op.f('idx_station_lines_line_order'), 'station_lines', ['line_id', 'station_order'], unique=False)
    op.create_index(op.f('idx_service_exceptions_service_date'), 'service_exceptions', ['service_id', 'service_date'], unique=False)
    op.create_index(op.f('idx_service_exceptions_date_category'), 'service_exceptions', ['service_date', 'exception_category'], unique=False)
    op.create_index(op.f('idx_service_exceptions_date'), 'service_exceptions', ['service_date'], unique=False)
    op.create_index(op.f('idx_service_calendar_date_range'), 'service_calendar', ['start_date', 'end_date'], unique=False)
    op.create_index(op.f('idx_routing_edges_current_from_to'), 'routing_edges_current', ['from_station_id', 'to_station_id'], unique=False)
    op.create_index(op.f('idx_routing_edges_current_base_edge_scenario_unique'), 'routing_edges_current', ['base_edge_id', 'scenario_id'], unique=True, postgresql_where='(scenario_id IS NOT NULL)')
    op.create_index(op.f('idx_routing_edges_current_base_edge_null_scenario_unique'), 'routing_edges_current', ['base_edge_id'], unique=True, postgresql_where='(scenario_id IS NULL)')
    op.create_index(op.f('idx_routing_edges_current_base_edge'), 'routing_edges_current', ['base_edge_id'], unique=False)
    op.create_index(op.f('idx_route_request_logs_created_at'), 'route_request_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint(None, 'predicted_stop_times', type_='foreignkey')
    op.create_index(op.f('predicted_stop_times_updated_at_idx'), 'predicted_stop_times', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_predicted_stop_times_trip_station_time'), 'predicted_stop_times', ['trip_id', 'station_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_predicted_stop_times_service_date_station'), 'predicted_stop_times', ['service_date', 'station_id', sa.literal_column('updated_at DESC')], unique=False)
    op.drop_constraint(None, 'next_departures', type_='foreignkey')
    op.drop_constraint(None, 'next_departures', type_='foreignkey')
    op.create_index(op.f('next_departures_updated_at_idx'), 'next_departures', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_next_departures_station_line_time'), 'next_departures', ['station_id', 'line_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_next_departures_service_date_station'), 'next_departures', ['service_date', 'station_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_next_departures_departure_at'), 'next_departures', ['predicted_departure_at'], unique=False)
    op.create_index(op.f('line_status_events_recorded_at_idx'), 'line_status_events', [sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_line_status_events_line_time'), 'line_status_events', ['line_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_line_status_events_line_effective'), 'line_status_events', ['line_id', sa.literal_column('effective_from DESC')], unique=False)
    op.create_index(op.f('idx_line_status_events_category_time'), 'line_status_events', ['event_category', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_line_status_current_status'), 'line_status_current', ['status'], unique=False)
    op.create_index(op.f('idx_holiday_dates_date'), 'holiday_dates', ['holiday_date'], unique=False)
    op.alter_column('etl_job_steps', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('etl_job_steps', 'status',
               existing_type=sa.Enum('running', 'success', 'failed', name='etl_job_status'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('idx_etl_job_runs_started_at', table_name='etl_job_runs')
    op.create_index(op.f('idx_etl_job_runs_started_at'), 'etl_job_runs', [sa.literal_column('started_at DESC')], unique=False)
    op.alter_column('etl_job_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('etl_job_runs', 'status',
               existing_type=sa.Enum('running', 'success', 'failed', name='etl_job_status'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_edges_to_station'), 'edges', ['to_station_id'], unique=False)
    op.create_index(op.f('idx_edges_line_to_order'), 'edges', ['line_id', 'to_station_order'], unique=False)
    op.create_index(op.f('idx_edges_line_from_order'), 'edges', ['line_id', 'from_station_order'], unique=False)
    op.create_index(op.f('idx_edges_line'), 'edges', ['line_id'], unique=False)
    op.create_index(op.f('idx_edges_from_station'), 'edges', ['from_station_id'], unique=False)
    op.create_index(op.f('idx_edge_status_events_edge_time'), 'edge_status_events', ['edge_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_index(op.f('idx_edge_status_events_edge_effective'), 'edge_status_events', ['edge_id', sa.literal_column('effective_from DESC')], unique=False)
    op.create_index(op.f('edge_status_events_recorded_at_idx'), 'edge_status_events', [sa.literal_column('recorded_at DESC')], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
